version: '3.5'

services:
  ixbird4:
    container_name: ixbird
    image: ghcr.io/ixp42/rs:master
    environment:
      - IXKEY=
      - IXHANDLE=rs-las-c-6
      - PORT=9001
      - IP4=169.254.1.1/24
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
    cap_add: 
      - NET_ADMIN
    networks:
      default:
      ixdockernet:
  ixbird6:
    container_name: ixbird
    image: ghcr.io/ixp42/rs:master
    environment:
      - IXKEY=
      - IXHANDLE=rs-las-c-6
      - PORT=9002
      - IP6=2a0e:b107:b7a::1/64
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
    cap_add: 
      - NET_ADMIN
    networks:
      default:
      ixdockernet:

networks:
  ixdockernet:
    name: 'ixdockernet'
    driver_opts:
      com.docker.network.bridge.name: ixdockernet
      com.docker.network.bridge.enable_ip_masquerade: 'false'
    driver: bridge
